name: Illustration
date: 12 Jan 2019
size: col-sm
hide: true
desc: >
  A small selection of illustrations, both recent and old.
metaTitle: A collection of illustrations by Stephen Hutchings

pageCount: 12

imgs:
  reveal: /img/projects/illustrations/illustration-reveal.png

tags:
  - Design
  - Posters
  - Illustration

image: "/img/page/illustrations.png"
