name: Monad Sans
date: 30 Nov 2015
size: col-md
desc: >
  Monad Sans is a family of typefaces in eight weights.
urls:
  -
    text: Purchase
    link: https://www.youworkforthem.com/font/T6230/monad-sans
imgs:
  cover:  /img/projects/monad-sans/cover.png
  reveal: /img/projects/monad-sans/reveal.png
tags:
  - Typography
  - Fonts
  - Design
