name: Monad Sans
date: 30 Nov 2015
size: col-md
desc: >
  Monad Sans is a type family in 8 weights
urls:
  -
    text: Specimen
    link: /monad/
    follow: true
imgs:
  cover:  /img/projects/monad-sans/cover.png
  reveal: /img/projects/monad-sans/reveal.png
