name: Nice to meet you.
date: 06 Mar 2015
size: col-md
desc: >
  Three hundred and eighty eight twist-tonguing people.
imgs:
  cover:  /img/projects/nice-to-meet-you/cover.png
  reveal: /img/projects/nice-to-meet-you/reveal.png
tags:
  - Design
