name: Nice to meet you.
date: 06 Mar 2015
size: col-md
desc: >
  Three hundred and eighty eight twist-tonguing people.
imgs:
  cover:  /img/projects/nice-to-meet-you/cover.png
  reveal: /img/projects/nice-to-meet-you/reveal.png
tags:
  - Design
pageCount: 11
text: |
  Mike and Ted, Ben, Jed and Dan
  Seth and Fran and Beth and Jan
  Clive and Clyde and Karl and Tim
  Kim, Anton, Kate, Tom and Jim
  Caroline and Chris and Tina
  Kirsty, Kristy, Sue, Christina
  Bram, Cat, Mathew, Beau & Martha
  John, Fred, Joe, Jack, Mo, Jay, Arthur
  Maurice, Boris, Janice, Morris
  Adonis, Doris, Chloë, Horace

  Otto, Dean, Xander, Hannah,
  Oscar, Jean and Kurt and Anna
  Mary Jane, Len, Kerry, Dane
  Lauren, Ella, Lex, Elaine
  Peter, Neil, Piper, Liam
  Ryan, Nathan, Nyrel, Ian
  Emma, Saffron. Dee, Sofia
  Abigail, Eva, Maria
  Madeleine and Agustina
  Valerie and Valentina

  Christo, Marvin, Louis, Jasper
  Matilda, Martin, Marcus, Casper
  Isobel, Mohammad, Charles
  Lou and Harry. Hugo, Lars
  James and Josh and Jake and Leo
  Claude, Maude, Jordan, Tord & Theo
  Elizabeth and Earl and Ethan
  Axel, Max, Hans, Bjørn and Stephen
  David, Dylan, Robin, Magnus
  Angus, Amar, Enzo, Agnes

  Aaron, Juan, Lucas, Noah
  Levi, Owen, Nolan, Jonah
  Heidi, Hetty, Emmanuelle
  Heather, Yousef, Hugh, Jóelle
  Dmitri, Dominic, Justine
  Alfred, Ines, Mel, Yasmine
  Clara, Sarah, Paula, Orla
  Lily, Ida, Frida, Laura
  Saeed, Saul and Solomon
  Polly, Donald, Bonnie, Ron

  Jiro, Xiao, Elijah, Ken
  Daphne, Deirdre, Damian
  Beck and Barney, Bobby, Brenda
  Sandra, Gladys, Sanjeev, Glenda
  Georgie, Jerry, Geraldine
  Ira, Ivor, Ty, Irene
  Tyrone, Tamsyn, Charlie, Trish
  Misha, Ricky, Mick, Hamish
  Travis, Liv, Mavis, Vera,
  Corey, Tosca, Scot, Samira

  Belle, Wolfgang, Belinda, Claire
  Donovan, Sal, Dot, Adair
  Stacy, Tracy, Macy, Stan
  Julie, June, Abdulrahman
  Leonard, Jenny, Yong, Yazmira
  Andy, Woo and Pru and Keira
  Stuart, Victor, Stig, Gustavo
  Greta, Bronwyn, Gabe and Paavo
  Delmar, Edward, Edwin, Finn
  Frank, Ferrari, Faith, Faye, Flynn

  Dennis, Dustin, Denzel, Deb
  Laurence, Sibyl, Libby, Seb
  Maggy, Reg, Peg, Gabrielle
  Adam, Lucy, Ariel
  Nancy, Aldous, Lois, Vlad
  Ernest, Marge, Albert, Asad
  Rudolph, William, Douglas, Larry
  Ralph and Wes, Jay, Leslie, Gary
  Virginia, José, Rose, and Vernon
  Hector, Jess, Jorge and Herman

  Rachel, Robert, Raul and Gina
  Roy and Gilbert, Romi, Mena
  Selma, Sally, May, Celine
  Thelma, Shelly, Sian, Marlene
  Greg and Meg and Dirk and Donny
  Berty, Jade, Bruno and Johnny
  Mitchell, Pam, Michelle and Pia
  Freja, Leif, Fern, Fleur and Mia
  Jared, Jacob, Giaconda
  Molly, Wanda, Wally, Rhonda

  Charlotte, Sharni, Silus, Shane
  Cheri, Sasha, Shay, Hussein
  Waleed, Jen, Janine, Yulanda
  Harold, Leland and Amanda
  Bernhard, Bob, Bartholomew
  Astrid, Toby, Art, Cy, Drew
  Sakura, Tony, Ruben, Sam
  Yuki, Andre, Diego, Cam
  Ashleigh, Basil, Angelina
  Barry, Tasha, Selby, Sheba

  Mona, Lana, Tori, Dora
  Diane, Marnie, Letty, Flora
  Garth, Minerva, Oswald, Rhys
  Desmond, Waldo, Beatrice
  Joanne, Rowan, Darlene, Carmen
  Simon, Warren, Zoran, Arman
  Ulric, Rex, Red, Eric, Ray
  Terrence, Blair, Tex, Patrick, Clay
  Piotr, Pedro, Perry, Paul
  Nice to meet you, one and all


# Mike and Ted, Ben, Jed and Dan
# Seth and Fran and Beth and Jan
# Pete and Paul, Mary, Tim
# Kim, Anton, Kate, Tom and Jim
# Caroline and Chris and Tina
# Kirsty, Kristy, Sue, Christina
# Sam and Beau, Mia, Martha
# John, Fred, Joe, Jack, Mo & Arthur
# Maurice, Boris, Janice, Morris
# Gabriella, Chloë, Horace
# Otto, Dean, Xander, Hannah,
# Oscar, Jean and Kurt and Anna
# Mary Jane, Kerry, Dane
# Laura, Lauren, Lex, Elaine
# Peter, Neil, Piper, Liam
# Pierre, Ryan, Nathan, Ian
# Emma, Saffron. Emile, Sofia
# Abigail, Ava, Maria
# Madeline and Agustina
# Valerie and Valentina
# Christoff, Marvin, Louis, Jasper
# Mathew, Martin, Marcus, Casper
# Isobel, Mohammad, Charles
# Hugh and Harry, Hugo, Lars
# James and Josh and Jake and Leo
# Claude, Maude, Jordan, Tord & Theo
# Elizabeth, Tracy, Ethan
# William-Max, Hans, Bjørn & Stephen
# David, Dylan, Robin, Magnus
# Angus, Amar, Enzo, Agnes
# Aaron, Juan, Lucas, Noah
# Levi, Owen, Nolan, Jonah
# Raphæl, Emmanuel
# Theresa, Yousef, Lou, Jóelle
# Dmitri, Dominic, Justine
# Alfred, Ines, Mel, Yasmine
# Clara, Sarah, Paula, Orla
# Lily, Ida, Frida, Laura
# Saeed, Saul and Solomon
# Nikita, Yuri, Polly, Ron
# Jiro, Hiro, Elijah, Ken
# Basil, Deirdre, Damian
# Sandra, Gladys, Sanjeev, Glen
# Barnaby and Magdelene
# Georgie, Jerry, Geraldine
# Ira, Ivor, Ty, Irene
# Tamsyn, Tyrone, Tippy, Trish
# Misha, Ricky, Mick, Hamish
# Travis, Liv, Mavis, Vera,
# Connor, Tosca, Scot, Samira
# Belle and Wolfgang, Belinda, Claire
# Donovan, Samantha, Cher
# Stacy, Tracy, Macy, Stan
# Julie, June, Abdulrahman
# Delmar, Edward, Edwin, Finn
# Frank, Ferrari, Faith, Faye, Flynn
# Leonard, Jenny, Yong, Yazmira
# Andrew, Woo and Pru and Keira
# Stuart, Victor, Stig, Gustavo
# Greta, Bronwyn, Gabe and Paavo
# Dennis, Dustin, Denzel, Deb
# Laurence, Sibyl, Libby, Seb
# Maggy, Peggy, Betty, Cadence
# Darren, Lucy, Doris, Patience
# Ray and Aldous, Lois, Vlad
# Ernest, Marge, Albert, Asad
# Eric, Adam, Douglas, Larry
# Ralph and Wes, Ray, Les and Gary
# Virginia, José, Rose, and Vernon
# Hector, Jess, Jorge and Herman
# Rachel, Robert, Raul and Gina
# Roy and Gilbert, Romi, Mena
# Selma, Sally, May, Celine
# Thelma, Shelly, Sian, Marlene
# Greg and Meg and Dirk and Donny
# Berty, Jade, Bruno and Johnny
# Mitchell, Pam, Michael, Pia
# Freja, Leif and Fern and Mia
# Jared, Jacob, Giaconda
# Molly, Wanda, Wally, Rhonda
# Nicolai and Stanislav,
# Ritchie, Guy and Miroslav
# Sharon, Jen and Yulanda
# Harold, Marty and Amanda
# Bernhard, Bob, Bartholomew
# Astrid, Toby, Art and Stu
# Sakura, Tony, Ruben, Bram
# Yuki, Andre, Diego, Pam
# Ashleigh, Daphne, Angelina
# Derrick, Tasha, Josefina
# Mona, Lana, Tori, Dora
# Diane, Marnie, Letty, Flora
# Garth, Minerva, Oswald, Rhys
# Desmond, Waldo, Beatrice
# Joanne, Rowan, Darlene, Carmen
# Simon, Warren, Zoran, Arman
# Ulric, Rex, Red, Eric, Ray
# Terrence, Blair, Tex, Patrick, Clay
# Piotr, Pedro, Perry, Paul
# Nice to meet you, one and all
