name: Gordian Knots
date: 20 Jun 2015
size: col-sm
hide: true
desc: >
  Gordian Knots are problems that prove impossible to untangle. This series of posters proves how easy it is to create huge complexity from a series of discrete, simple steps.

metaTitle: Gordian Knots - Impossible Posters by Stephen Hutchings

pageCount: 5

imgs: {}

tags:
  - Design
  - Posters
