name: "Médecins Sans Fron&shy;tières"
date: 06 Mar 2015
size: col-md
hide: true
desc: >
  Working with global charity MSF this microsite successfully helped  promote current issues and drive donations from a younger  demographic.
imgs:
  cover:  /img/projects/msf/cover.png
  reveal: /img/projects/msf/reveal.png
