name: Ed Sans
date: 20 Jun 2015
size: col-sm
desc: >
  Ed Sans is designed for legibility and neutrality, but small tweaks give it
  the warmth & style it needs to make the right impression. The font was
  developed as an integral part of the broader design strategy for
  [Ed](https://www.edapp.com).
metaTitle: Ed Sans - Corporate Typeface by Stephen Hutchings
pageCount: 4

font:
  name: "edsansneue"
  path: "/fonts/ed-sans/"
  variants:
    - name: semibold
      weight: 600
    - name: semibolditalic
      weight: 600
      style: italic
    - name: light
      weight: 300
    - name: regular
      weight: 400
    - name: medium
      weight: 500
    - name: bold
      weight: 700
    - name: lightitalic
      weight: 300
      style: italic
    - name: bolditalic
      weight: 700
      style: italic
    - name: regularitalic
      weight: 400
      style: italic

icons:
  - code: "\\F101"
    title: "Play"
    name: "play"
  - code: "\\F103"
    title: "Pause"
    name: "pause"
  - code: "\\F104"
    title: "Mute"
    name: "volume-mute"
  - code: "\\F105"
    title: "Low Vol."
    name: "volume-low"
  - code: "\\F106"
    title: "Mid Vol."
    name: "volume-mid"
  - code: "\\F107"
    title: "High Vol."
    name: "volume-high"
  - code: "\\F108"
    title: "Expand"
    name: "fullscreen-enter"
  - code: "\\F109"
    title: "Contract"
    name: "fullscreen-exit"
  - code: "\\F10B"
    title: "Spinner"
    name: "spinner"
  - code: "\\F10C"
    title: "Subtitles"
    name: "subtitles"
  - code: "\\F10D"
    title: "Captions"
    name: "captions"
  - code: "\\F114"
    title: "HD Video"
    name: "hd"
  - code: "\\F10E"
    title: "Chapters"
    name: "chapters"
  - code: "\\F10F"
    title: "Share"
    name: "share"
  - code: "\\F110"
    title: "Settings"
    name: "cog"
  - code: "\\F111"
    title: "Circle"
    name: "outer-circle"
  - code: "\\F112"
    title: "Open Circle"
    name: "circle-outline"
  - code: "\\F10A"
    title: "Square"
    name: "square"
  - code: "\\F116"
    title: "Replay"
    name: "replay"
  - code: "\\F11D"
    title: "Audio Description"
    name: "audio-description"
  - code: "\\F11E"
    title: "Audio"
    name: "headphones"
  - code: "\\F11F"
    title: "Cancel"
    name: "cancel"
  - code: "\\F120"
    title: "Zoom In"
    name: "zoom-in"
  - code: "\\F121"
    title: "Zoom Out"
    name: "zoom-out"
  - code: "\\F122"
    title: "Left"
    name: "arrow-left"
  - code: "\\F123"
    title: "Right"
    name: "arrow-right"
  - code: "\\F137"
    title: "Back"
    name: "back"
  - code: "\\F124"
    title: "Forward"
    name: "forward"
  - code: "\\F125"
    title: "Star"
    name: "star"
  - code: "\\F126"
    title: "Lock"
    name: "lock"
  - code: "\\F128"
    title: "Left LG"
    name: "chevron-left"
  - code: "\\F127"
    title: "Right LG"
    name: "chevron-right"
  - code: "\\F129"
    title: "Up LG"
    name: "chevron-up"
  - code: "\\F12A"
    title: "Down LG"
    name: "chevron-down"
  - code: "\\F12B"
    title: "Menu"
    name: "menu"
  - code: "\\F102"
    title: "Video"
    name: "video"
  - code: "\\F12C"
    title: "Tick Badge"
    name: "circle-tick"
  - code: "\\F12D"
    title: "Cross Badge"
    name: "circle-cross"
  - code: "\\F12E"
    title: "Plus"
    name: "plus"
  - code: "\\F12F"
    title: "Minus"
    name: "minus"
  - code: "\\F130"
    title: "Pencil"
    name: "pencil"
  - code: "\\F131"
    title: "Drag X"
    name: "drag"
  - code: "\\F140"
    title: "Drag Y"
    name: "drag-vertical"
  - code: "\\F132"
    title: "Bullet"
    name: "inner-circle"
  - code: "\\F133"
    title: "Chat"
    name: "chat"
  - code: "\\F134"
    title: "Chat Count"
    name: "chat-count"
  - code: "\\F135"
    title: "Heart"
    name: "heart"
  - code: "\\F136"
    title: "Flag"
    name: "flag"
  - code: "\\F138"
    title: "Calendar"
    name: "calendar"
  - code: "\\F139"
    title: "Chart"
    name: "chart"
  - code: "\\F13A"
    title: "Clock"
    name: "clock"
  - code: "\\F13B"
    title: "Cloud"
    name: "cloud"
  - code: "\\F13C"
    title: "Delete"
    name: "delete"
  - code: "\\F13D"
    title: "Document"
    name: "document"
  - code: "\\F13E"
    title: "Download"
    name: "download"
  - code: "\\F13F"
    title: "Upload"
    name: "upload"
  - code: "\\F141"
    title: "Draft"
    name: "eye-closed"
  - code: "\\F142"
    title: "Publish"
    name: "eye-open"
  - code: "\\F143"
    title: "Image"
    name: "image"
  - code: "\\F144"
    title: "Image Reversed"
    name: "image-reversed"
  - code: "\\F145"
    title: "Information"
    name: "info"
  - code: "\\F146"
    title: "Warning"
    name: "warning"
  - code: "\\F147"
    title: "Mail"
    name: "mail"
  - code: "\\F148"
    title: "Package"
    name: "package"
  - code: "\\F149"
    title: "Record"
    name: "record"
  - code: "\\F14C"
    title: "Align Center"
    name: "text-center"
  - code: "\\F14D"
    title: "Align Left"
    name: "text-left"
  - code: "\\F14E"
    title: "Align Right"
    name: "text-right"
  - code: "\\F14F"
    title: "WiFi"
    name: "wifi"
  - code: "\\F151"
    title: "Cross"
    name: "cross"
  - code: "\\F152"
    title: "Tick"
    name: "tick"
  - code: "\\F154"
    title: "Left SM"
    name: "left-sm"
  - code: "\\F156"
    title: "Right SM"
    name: "right-sm"
  - code: "\\F155"
    title: "Up SM"
    name: "up-sm"
  - code: "\\F153"
    title: "Down SM"
    name: "down-sm"
  - code: "\\F157"
    title: "Bold"
    name: "bold"
  - code: "\\F158"
    title: "Italic"
    name: "italic"
  - code: "\\F14B"
    title: "Text"
    name: "text"
  - code: "\\F14A"
    title: "Search"
    name: "search"
  - code: "\\F150"
    title: "Ed"
    name: "ed"

image: "/img/page/ed-sans.png"
