name: "zepto.ios&shy;tap"
date: 01 Feb 2014
size: col-sm
desc: >
  A micro library for “native” feeling tap events in the browser.
urls:
  -
    text: GitHub
    link: http://github.com/stephenhutchings/zepto.iostap/
imgs:
  cover:  /img/projects/iostap/cover.png
  reveal: /img/projects/iostap/reveal.png
