name: "iostap"
date: 01 Feb 2014
size: col-sm
desc: >
  A micro library for “native” feeling tap events in the browser.
urls:
  -
    text: GitHub
    link: http://github.com/stephenhutchings/iostap/
  -
    text: NPM
    link: http://npmjs.com/iostap/
  -
    text: Demo
    link: http://stephenhutchings.github.com/iostap/demo/
imgs:
  cover:  /img/projects/iostap/cover.png
  reveal: /img/projects/iostap/reveal.png
tags:
  - UI/UX
