name: Fire Truck
date: 03 Jul 2014
size: col-sm
desc: >
  Concept toy truck laser-cut from bamboo ply
imgs:
  cover:  /img/projects/fire-truck/cover.png
  reveal: /img/projects/fire-truck/reveal.png
tags:
  - Ponoko
  - Design
