name: Asterisms
date: 20 Jun 2015
size: col-sm
desc: >
  Asterisms charts the night sky in a beautifully detailed poster.
  Using a clever projection which maps both hemispheres onto a circle,
  it offers a combined view of the northern and sourthen skies.
metaTitle: Asterisms - Sky Chart Poster Design by Stephen Hutchings

pageCount: 3

imgs:
  cover:  /img/projects/asterisms/cover.png
  reveal: /img/projects/asterisms/reveal.png

colors:
  # highlight: "#deac74 !important"
  dark: "#191919"
  # light: "#f9f6f2"

tags:
  - Design
  - Posters

image: "/img/page/asterisms.png"
