name: console.log
date: 24 Aug 2016
size: col-lg
desc: >
  A series of computer generated drawings capturing the natural,  stylised technique of a  skilled&nbsp;illustrator.

imgs:
  cover:  /img/projects/console-log/cover.png
  reveal: /img/projects/console-log/reveal.png
tags:
  - Design
  - Posters
